### ISSUE TITLE
request with http

### ISSUE THREAD

**Issue by lostpupil** [dduan/Just#47]
If I post to https url, it will post with ip:443, but I use nginx as a reverse proxy server, so ti wont send request to ip.

**Comment by dduan** [comment]
Is this an issue related to Just?

**Comment by lostpupil** [comment]
I think it is, if I use alamofire, it will sent request like https://baidu.com/action but this framework will send request like 192.168.0.1:443.

**Comment by goribchat** [comment]
Authentication is not happening ,please help..
This is my response message.
here is my code
let params = ["username" : email, "password": password] as [String : Any]

    print("type ::\(params)")
    
    Just.post(Constant.url.login1,params: params) { (r) in
        if !r.ok {
            print(r.text!)
            
        }
        else{
            
            let json = r.text!
            print(json)
            let login = Mapper<UserRoot>().map(JSONString: json)
            let errorValue = login?.success
            self.userDetails1 =  login?.details
            DispatchQueue.main.async {
                if errorValue == true {
                    self.userDetails1.backup = self.passwordTF.text!
                    self.passwordTF.text = ""
                }
                else if errorValue == false {
                   
                }
            }
        }
    but after giving proper login credentials it is showing that username password is wrong. please help..
