### ISSUE TITLE
Official Support for Swift 4

### ISSUE THREAD

**Issue by stevapple** [dduan/Just#93]
Merge the current master branch into 'swift-3.1' and merge the 'swift-4' branch into master.

**Comment by eugeneyakub** [comment]
Hello. Swift-4 branch works well. Could someone merge? =) I hope library is not deprecated.

**Comment by goribchat** [comment]
is it supportable for swift 4?

**Comment by goribchat** [comment]
i have use just in swift 8.3.3.it works well there, but problem has occur in swift 4. in authenticating. can some body help me?
